version: '2'
services:
  jordan-hatcher.com:
    image: latest-hugo:latest
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=jordan-hatcher.com,www.jordan-hatcher.com
      - HUGO_BASE_URL=https://jordan-hatcher.com
      - HUGO_PORT=80
      - HUGO_BIND=0.0.0.0
    volumes:
      - website-data:/data
    network_mode: bridge
    restart: always

  jordan-hatcher-listener:
    image: listener:latest
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=webhook.jordan-hatcher.com
    volumes:
      - /home/jordan/storage/listener-config/config.json:/src/config.json
      - website-data:/data
    network_mode: bridge
    restart: always
volumes:
  website-data:
