baseURL = "jordan-hatcher.com"
languageCode = "en-us"
title = "Jordan Hatcher"
theme = "hemingway"

[params]

[params.highlight]
style = "dracula"

[[params.social]]
url = "https://github.com/jordanhatcher"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/jrdhtc"
fa_icon = "fa-twitter"
